table AggDelinquencyRoll

	column MonthKey
		dataType: int64
		summarizeBy: none
		sourceColumn: MonthKey

	column PrevBucket
		dataType: string
		summarizeBy: none
		sourceColumn: PrevBucket

	column DelinquencyBucket
		dataType: string
		summarizeBy: none
		sourceColumn: DelinquencyBucket

	column AccountCount
		dataType: int64
		summarizeBy: sum
		sourceColumn: AccountCount

	column BalanceMoved
		dataType: double
		summarizeBy: sum
		sourceColumn: BalanceMoved
		formatString: #,0.00

	partition AggDelinquencyRoll = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "AggDelinquencyRoll.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"MonthKey", Int64.Type}, {"PrevBucket", type text}, {"DelinquencyBucket", type text}, {"AccountCount", Int64.Type}, {"BalanceMoved", type number}})
				in
					Typed
