table AggDailyDeposits

	column DateKey
		dataType: int64
		summarizeBy: none
		sourceColumn: DateKey

	column BranchKey
		dataType: int64
		summarizeBy: none
		sourceColumn: BranchKey

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey

	column TotalDeposits
		dataType: double
		summarizeBy: sum
		sourceColumn: TotalDeposits
		formatString: #,0.00

	column DepositAccounts
		dataType: int64
		summarizeBy: sum
		sourceColumn: DepositAccounts

	partition AggDailyDeposits = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "AggDailyDeposits.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"DateKey", Int64.Type}, {"BranchKey", Int64.Type}, {"ProductKey", Int64.Type}, {"TotalDeposits", type number}, {"DepositAccounts", Int64.Type}})
				in
					Typed
