table AggMonthlyLoans
	column MonthKey
		dataType: int64
		summarizeBy: none
		sourceColumn: MonthKey
	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey
	column LineOfBusiness
		dataType: string
		summarizeBy: none
		sourceColumn: LineOfBusiness
	column LoanBalance
		dataType: double
		summarizeBy: sum
		sourceColumn: LoanBalance
		formatString: #,0.00
	column InterestIncome
		dataType: double
		summarizeBy: sum
		sourceColumn: InterestIncome
		formatString: #,0.00
	column NPLBalance
		dataType: double
		summarizeBy: sum
		sourceColumn: NPLBalance
		formatString: #,0.00
	partition AggMonthlyLoans = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "AggMonthlyLoans.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"MonthKey", Int64.Type}, {"ProductKey", Int64.Type}, {"LineOfBusiness", type text}, {"LoanBalance", type number}, {"InterestIncome", type number}, {"NPLBalance", type number}})
				in
					Typed