table AggMonthlyDeposits
	column MonthKey
		dataType: int64
		summarizeBy: none
		sourceColumn: MonthKey
	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey
	column LineOfBusiness
		dataType: string
		summarizeBy: none
		sourceColumn: LineOfBusiness
	column DepositBalance
		dataType: double
		summarizeBy: sum
		sourceColumn: DepositBalance
		formatString: #,0.00
	column InterestExpense
		dataType: double
		summarizeBy: sum
		sourceColumn: InterestExpense
		formatString: #,0.00
	partition AggMonthlyDeposits = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "AggMonthlyDeposits.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"MonthKey", Int64.Type}, {"ProductKey", Int64.Type}, {"LineOfBusiness", type text}, {"DepositBalance", type number}, {"InterestExpense", type number}})
				in
					Typed