table DimProduct

	column ProductKey
		dataType: int64
		isKey
		summarizeBy: none
		sourceColumn: ProductKey

	column ProductCode
		dataType: string
		summarizeBy: none
		sourceColumn: ProductCode

	column ProductName
		dataType: string
		summarizeBy: none
		sourceColumn: ProductName

	column ProductCategory
		dataType: string
		summarizeBy: none
		sourceColumn: ProductCategory

	column LineOfBusiness
		dataType: string
		summarizeBy: none
		sourceColumn: LineOfBusiness

	column BaseRate
		dataType: double
		summarizeBy: sum
		sourceColumn: BaseRate
		formatString: #,0.00

	partition DimProduct = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "DimProduct.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"ProductKey", Int64.Type}, {"ProductCode", type text}, {"ProductName", type text}, {"ProductCategory", type text}, {"LineOfBusiness", type text}, {"BaseRate", type number}})
				in
					Typed
