table FactTransaction

	column TransactionID
		dataType: string
		summarizeBy: none
		sourceColumn: TransactionID

	column DateKey
		dataType: int64
		summarizeBy: none
		sourceColumn: DateKey

	column TxnTimestamp
		dataType: dateTime
		summarizeBy: none
		sourceColumn: TxnTimestamp

	column AccountKey
		dataType: int64
		summarizeBy: none
		sourceColumn: AccountKey

	column CustomerKey
		dataType: int64
		summarizeBy: none
		sourceColumn: CustomerKey

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey

	column BranchKey
		dataType: int64
		summarizeBy: none
		sourceColumn: BranchKey

	column TransactionType
		dataType: string
		summarizeBy: none
		sourceColumn: TransactionType

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel

	column MerchantCategory
		dataType: string
		summarizeBy: none
		sourceColumn: MerchantCategory

	column Amount
		dataType: double
		summarizeBy: sum
		sourceColumn: Amount
		formatString: #,0.00

	column IsFraudFlag
		dataType: boolean
		summarizeBy: none
		sourceColumn: IsFraudFlag

	column Direction
		dataType: string
		summarizeBy: none
		sourceColumn: Direction

	column AbsAmount
		dataType: double
		summarizeBy: sum
		sourceColumn: AbsAmount
		formatString: #,0.00

	partition FactTransaction = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "FactTransaction.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"TransactionID", type text}, {"DateKey", Int64.Type}, {"TxnTimestamp", type datetime}, {"AccountKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"BranchKey", Int64.Type}, {"TransactionType", type text}, {"Channel", type text}, {"MerchantCategory", type text}, {"Amount", type number}, {"IsFraudFlag", type logical}, {"Direction", type text}, {"AbsAmount", type number}})
				in
					Typed
